---
title: "Segment stats"
author: "Henrik Nordtorp"
date: '`r Sys.Date()`'
output: html_document
---

```{r}
knitr::opts_chunk$set(dpi=300)
```


```{r}
library(pedtools)
library(ibdrel)
library(ibdsim2)
library(ggplot2)
library(forcats)
library(dplyr)
library(paletteer)

segmentranges <- function(pedlist) {

  df = data.frame(ped = character(),
                  rel = character(),
                  type = character(),
                  deg = factor(),
                  pathn = factor(),
                  mean = numeric())
  allsegs = list()

  for (i in 1:length(pedlist)) {
    ped = pedlist[[i]]
    rel = strsplit(ibdrel::annotatePedigree(ped), "-")[[1]][1]
    verb = verbalisr::verbalise(ped, ids = ibdrel::identifyLeaves(ped))[[1]]
    deg = verb$degree
    
    if (isTRUE(verb$full)) {
      type = verb$type
    } else {
      type = verb$type
      if (type == "lineal") {
        type = "direct"
      } else {
        type = "half-cousin"
      }
    }
    
    pathn = length(strsplit(verb$sexPath, "")[[1]])
    
    variants = pedVariants(ped)
    peds = ibdrel::constructPedigrees(variants)

    annotation = sapply(peds, ibdrel:::annotatePedigree)
    sims_training <- ibdrel:::ibdSimulations(peds, N = 500, seed = NULL)
    segments <- ibdrel:::lengthIBD(sims_training, peds, annotation)

    sapply(segments, function(x) {
      unlist(x) |> mean()
    }) -> means
    
    segs <- lapply(segments, function(x) {
      unlist(x)
    })
    
    allsegs[names(means)] <- segs
    
    npeds = length(annotation)
    

    df <- rbind(df, data.frame(ped = annotation,
                               rel = rep(rel, npeds),
                               type = rep(type, npeds),
                               deg = rep(deg, npeds),
                               pathn = rep(pathn, npeds),
                               mean = means))
  }

  return (list(df = df, allsegs = allsegs))
}
```

```{r message=FALSE}
lpeds <- list(linearPed(2), linearPed(3), linearPed(4), linearPed(5),
              linearPed(6), linearPed(7), linearPed(8), linearPed(9),
              linearPed(10), linearPed(11))
couspeds <- list(cousinPed(1), cousinPed(1, 1), cousinPed(2), cousinPed(2,1), cousinPed(3), cousinPed(3, 1), cousinPed(4), cousinPed(4, 1), cousinPed(5))
hcouspeds <- list(avuncularPed(removal = 1), cousinPed(1, half = T), cousinPed(1, 1, half = T),
                  cousinPed(2, half = T), cousinPed(2, 1, half = T),
                  cousinPed(3, half = T), cousinPed(3, 1, half = T),
                  cousinPed(4, half = T), cousinPed(4, 1, half = T))
avpeds <- list(avuncularPed(removal = 1), avuncularPed(removal = 2), avuncularPed(removal = 3), avuncularPed(removal = 4), avuncularPed(removal = 5), avuncularPed(removal = 6),
               avuncularPed(removal = 7), avuncularPed(removal = 8), avuncularPed(removal = 9), avuncularPed(removal = 10))
#havpeds <- list(avuncularPed(removal = 1, half = T), avuncularPed(removal = 2, half = T), avuncularPed(removal = 3, half = T), avuncularPed(removal = 4, half = T)) In equivalence with half cous peds

lranges <- segmentranges(lpeds)
cousranges <- segmentranges(couspeds)
hcousranges <- segmentranges(hcouspeds)
avpedranges <- segmentranges(avpeds)
#havpedranges <- segmentranges(havpeds)

pedranges <- rbind(lranges$df, cousranges$df, hcousranges$df, avpedranges$df)
```

```{r}
pedranges <- pedranges |> 
  mutate(type = factor(type,
                       levels = c("direct", "half-cousin", "avuncular", "cousin")))

endpoints <- pedranges |>
  group_by(rel, type, deg) |> 
  summarise(lower_variant = ped[which.min(mean)],
            lower_value = min(mean),
            upper_variant = ped[which.max(mean)],
            upper_value = max(mean),
            .groups = "drop") |> 
  mutate(lower_symbol = "♀",
         upper_symbol = "♂") |> 
  mutate(deg = factor(deg))

midpoints <- pedranges |> 
  left_join(endpoints, by = "rel") |> 
  filter(mean != lower_value & mean != upper_value) |> 
  mutate(type = type.x,
         deg = factor(deg.x))

offset <- 0.125
ggplot() +
  geom_linerange(data = endpoints, mapping = aes(y = fct_reorder(deg, upper_value, .desc = T), xmin = lower_value+offset, xmax = upper_value,
                                                 colour = factor(deg)),
                 alpha = .5, linewidth = 1.5) +
  geom_point(data = midpoints, aes(x = mean, y = deg, colour = factor(deg)),
             show.legend = FALSE) +
  geom_text(data = endpoints, aes(x = lower_value, y = deg, label = lower_symbol,
                                  colour = factor(deg)),
            size = 5, show.legend = FALSE) +
  geom_text(data = endpoints, aes(x = upper_value, y = deg, label = upper_symbol,
                                  colour = factor(deg)),
            size = 5, show.legend = FALSE) +
  facet_grid(rows = vars(type), scales = "free_y", switch = "y") +
  labs(x = "Mean segment length (cM)",
       y = "Degree",
       colour = "Degree") +
  scale_x_continuous(breaks = c(seq(5,70, by = 5)),
                     limits = c(5, 70),
                     transform = "log2") +
  scale_colour_paletteer_d("MoMAColors::Klein") +
  theme_bw(base_size = 14) +
  theme(legend.position = "none",
        axis.text.x = element_text(size = 9),
        axis.text.y = element_text(size = 9)) -> rangeplot

rangeplot

ggsave("figures/rangeplot.pdf", plot = rangeplot, dpi = 600, device = cairo_pdf, width = 9, height = 9)
```


```{r}
pedranges$type[1:4] <- "direct"
ggplot(pedranges) +
  geom_linerange(aes(y = fct_reorder(rel, deg), xmin = xstart, xmax = xend,  colour = factor(deg)),
                 size = 1.5, alpha = .5) +
  geom_point(aes(x = xstart, y = rel, colour = factor(deg))) +
  geom_point(aes(x = xend, y = rel, colour = factor(deg))) +
  facet_grid(rows = vars(type), switch = "y", space = "free_y", scales= "free_y") +
  labs(x = "Mean segment length",
       y = "Relationship") +
  theme_bw() 
```

What about change relative to the number of positions?
- Plot "number of males/females vs mean segment length".

```{r}
pedranges$range <- pedranges$xend - pedranges$xstart
pedranges$meanrange <- pedranges$range / pedranges$pathn

ggplot(pedranges) +
  geom_point(aes(x = deg, y = meanrange)) +
  geom_line(aes(x = deg, y = pathn)) +
  geom_smooth(aes(x = deg, y = meanrange)) +
  labs(x = "Degree", y = "Average segment mean range") +
  theme_bw()
```

Percentwise change per position in the pedigree path?


Individual segments:

```{r}
lranges$allsegs |> stack() |> 
  ggplot() +
  geom_boxplot(aes(x = values, y = ind)) +
  labs(x = "Segment length", y = "Relationship") +
  theme_bw()
```


## Differences in IBD distributions

L2-p vs L2-m
```{r}
l2.p <- ecdf(lranges$allsegs$`L2-p`)
l2.m <- ecdf(lranges$allsegs$`L2-m`)

grid <- seq(0,250,by=0.01)
plot(grid, l2.p(grid), type = "l", col = "blue")
lines(grid, l2.m(grid), type = "l", col = "red")

ks.test(lranges$allsegs$`L2-p`, lranges$allsegs$`L2-m`)
```


L5-m vs L5-p
```{r}
l5.p <- ecdf(lranges$allsegs$`L5-p`)
l5.m <- ecdf(lranges$allsegs$`L5-m`)

grid <- seq(0,250,by=0.01)
plot(grid, l5.p(grid), type = "l", col = "blue")
lines(grid, l5.m(grid), type = "l", col = "red")

ks.test(lranges$allsegs$`L5-p`, lranges$allsegs$`L5-m`)
```

L5-mmmp vs L5-mmpp
```{r}
l5.mmmp <- ecdf(lranges$allsegs$`L5-mmmp`)
l5.mmpp <- ecdf(lranges$allsegs$`L5-mmpp`)

grid <- seq(0,250,by=0.01)
plot(grid, l5.mmmp(grid), type = "l", col = "blue")
lines(grid, l5.mmpp(grid), type = "l", col = "red")

ks.test(lranges$allsegs$`L5-mmmp`, lranges$allsegs$`L5-mmpp`)
```

